### ISSUE TITLE
Trigger executions fail on wemo miscommunication

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/dowhen#2]
Everything shouldn't die if one device can't be communicated with:

    Traceback (most recent call last):
      File "/home/dowhen/.local/lib/python3.6/site-packages/dowhen/common/daemon.py", line 62, in run_daemon
        do(event[1], event[2])
      File "/home/dowhen/.local/lib/python3.6/site-packages/dowhen/common/daemon.py", line 30, in do
        return func(**kwargs)
      File "/home/dowhen/.local/lib/python3.6/site-packages/dowhen/do/wemo/__init__.py", line 26, in off
        return device_off(mac)
      File "/home/dowhen/.local/lib/python3.6/site-packages/dowhen/do/wemo/comm.py", line 61, in device_off
        return dev.off()
      File "/home/dowhen/.local/lib/python3.6/site-packages/pywemo/ouimeaux_device/switch.py", line 16, in off
        return self.set_state(0)
      File "/home/dowhen/.local/lib/python3.6/site-packages/pywemo/ouimeaux_device/switch.py", line 11, in set_state
        self.basicevent.SetBinaryState(BinaryState=int(state))
      File "/home/dowhen/.local/lib/python3.6/site-packages/pywemo/ouimeaux_device/api/service.py", line 88, in __call__
        "Giving up.".format(self._device.name, MAX_RETRIES))
    pywemo.ouimeaux_device.api.service.ActionException: Error communicating with Living room plant right after 3 attempts.>

Should probably move these to a queue with retries, but maybe that can be later.  At the very least, these exceptions should not fail the whole chain.

**Comment by mikeshultz** [comment]
Exceptions handled in 0357b0e

**Comment by mikeshultz** [comment]
Retries added in e5f2a6c
